# Generated by Django 6.0.6 on 2026-07-20 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas', '0005_remove_admarea_adm_areas_parent_level_name_uniq_and_more'),
        ('commodities', '0003_commodityunit_commodity_unit_ref'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('admin_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='markets', to='areas.admarea')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_markets', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_markets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'markets',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MarketCommodityPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='UGX', max_length=3)),
                ('price_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_prices', to='commodities.commodity')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_market_commodity_prices', to=settings.AUTH_USER_MODEL)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commodity_prices', to='markets.market')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_market_commodity_prices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'market_commodities_prices',
                'ordering': ['-price_date', 'market__name', 'commodity__name'],
            },
        ),
        migrations.AddIndex(
            model_name='market',
            index=models.Index(fields=['admin_area', 'status'], name='markets_area_status_idx'),
        ),
        migrations.AddIndex(
            model_name='market',
            index=models.Index(fields=['name'], name='markets_name_idx'),
        ),
        migrations.AddIndex(
            model_name='marketcommodityprice',
            index=models.Index(fields=['market', 'price_date'], name='mcp_market_date_idx'),
        ),
        migrations.AddIndex(
            model_name='marketcommodityprice',
            index=models.Index(fields=['commodity', 'price_date'], name='mcp_commodity_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='marketcommodityprice',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('market', 'commodity', 'price_date'), name='market_commodity_price_unique'),
        ),
    ]
