# Generated by Django 6.0.6 on 2026-07-31 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0004_marketcommodityprice_price_usd_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='marketcommodityprice',
            table='commodities_prices',
        ),
    ]
