# Generated by Django 6.0.6 on 2026-07-31 09:27

from django.conf import settings
from django.db import migrations, models


def migrate_pricetype_values_to_snake_case(apps, schema_editor):
    MarketCommodityPrice = apps.get_model('markets', 'MarketCommodityPrice')
    # Update existing values to snake_case in legacy DB before column drop/rename
    MarketCommodityPrice.objects.filter(pricetype='Retail').update(pricetype='retail')
    MarketCommodityPrice.objects.filter(pricetype='Wholesale').update(pricetype='wholesale')


def populate_null_market_codes(apps, schema_editor):
    Market = apps.get_model('markets', 'Market')
    for i, market in enumerate(Market.objects.filter(code__isnull=True)):
        market.code = f"temp_code_{market.id}_{i}"
        market.save(update_fields=['code'])


def create_native_postgres_enums(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        old_autocommit = schema_editor.connection.autocommit
        schema_editor.connection.autocommit = True
        try:
            with schema_editor.connection.cursor() as cursor:
                cursor.execute("SELECT 1 FROM pg_type WHERE typname = 'currency_enum'")
                if not cursor.fetchone():
                    cursor.execute("CREATE TYPE currency_enum AS ENUM ('USD', 'TZS')")

                cursor.execute("SELECT 1 FROM pg_type WHERE typname = 'price_type_enum'")
                if not cursor.fetchone():
                    cursor.execute("CREATE TYPE price_type_enum AS ENUM ('retail', 'wholesale')")

                cursor.execute("""
                    ALTER TABLE commodities_prices 
                    ALTER COLUMN price_type TYPE price_type_enum 
                    USING price_type::price_type_enum
                """)

                cursor.execute("""
                    ALTER TABLE commodities_prices 
                    ALTER COLUMN currency TYPE currency_enum 
                    USING currency::currency_enum
                """)
        finally:
            schema_editor.connection.autocommit = old_autocommit


def remove_native_postgres_enums(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        old_autocommit = schema_editor.connection.autocommit
        schema_editor.connection.autocommit = True
        try:
            with schema_editor.connection.cursor() as cursor:
                cursor.execute("ALTER TABLE commodities_prices ALTER COLUMN price_type TYPE varchar(32) USING price_type::varchar")
                cursor.execute("ALTER TABLE commodities_prices ALTER COLUMN currency TYPE varchar(3) USING currency::varchar")
                cursor.execute("DROP TYPE IF EXISTS price_type_enum")
                cursor.execute("DROP TYPE IF EXISTS currency_enum")
        finally:
            schema_editor.connection.autocommit = old_autocommit


def populate_new_price_type_column(apps, schema_editor):
    MarketCommodityPrice = apps.get_model('markets', 'MarketCommodityPrice')
    for price in MarketCommodityPrice.objects.all().iterator():
        new_val = None
        if price.pricetype:
            new_val = price.pricetype.lower()
            if new_val not in ['retail', 'wholesale']:
                new_val = 'retail'
        price.price_type = new_val
        price.save(update_fields=['price_type'])


class Migration(migrations.Migration):
    
    # Force Django to run this migration outside of a transaction to prevent the OperationalError
    atomic = False

    dependencies = [
        ('commodities', '0007_alter_commodityunitmap_id'),
        ('markets', '0005_alter_marketcommodityprice_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='marketcommodityprice',
            name='market_commodity_price_unique',
        ),
        migrations.RemoveIndex(
            model_name='market',
            name='markets_area_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='market',
            name='markets_name_idx',
        ),
        migrations.AddField(
            model_name='marketcommodityprice',
            name='price_type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        # Step 1: Migrate values to lower case in old pricetype field
        migrations.RunPython(
            migrate_pricetype_values_to_snake_case,
            reverse_code=migrations.RunPython.noop,
        ),
        # Step 2: Populate the newly added price_type field prior to dropping old columns
        migrations.RunPython(
            populate_new_price_type_column,
            reverse_code=migrations.RunPython.noop,
        ),
        # Step 3: Populate null market codes to satisfy database constraints
        migrations.RunPython(
            populate_null_market_codes,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='market',
            name='code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='market',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='status',
            field=models.CharField(default='active', max_length=50),
        ),
        # Step 4: Drop the old fields so their varchar schema doesn't interfere
        migrations.RemoveField(
            model_name='marketcommodityprice',
            name='price_usd',
        ),
        migrations.RemoveField(
            model_name='marketcommodityprice',
            name='pricetype',
        ),
        # Step 5: Run Postgres native enum migration mapping values to currency_enum and price_type_enum
        migrations.RunPython(
            create_native_postgres_enums,
            reverse_code=remove_native_postgres_enums,
        ),
        migrations.AddConstraint(
            model_name='marketcommodityprice',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('market', 'commodity', 'price_date', 'price_type'), name='market_commodity_price_unique'),
        ),
    ]
