# Generated by Django 6.0.6 on 2026-07-31 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0006_remove_marketcommodityprice_market_commodity_price_unique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketcommodityprice',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='marketcommodityprice',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('TZS', 'TZS')], default='TZS', max_length=3),
        ),
        migrations.AlterField(
            model_name='marketcommodityprice',
            name='price_type',
            field=models.CharField(blank=True, choices=[('retail', 'retail'), ('wholesale', 'wholesale')], max_length=32, null=True),
        ),
    ]
