# Generated by Django 6.0.6 on 2026-07-31 09:52

import django.db.models.deletion
from django.db import migrations, models


def set_default_commodity_unit_ids(apps, schema_editor):
    MarketCommodityPrice = apps.get_model('markets', 'MarketCommodityPrice')
    CommodityUnitMap = apps.get_model('commodities', 'CommodityUnitMap')
    CommodityUnit = apps.get_model('commodities', 'CommodityUnit')

    # Get a fallback unit just in case
    fallback_unit = CommodityUnit.objects.first()

    for price in MarketCommodityPrice.objects.all().iterator():
        primary_map = CommodityUnitMap.objects.filter(commodity=price.commodity, is_primary=True).first()
        target_unit = primary_map.unit if primary_map else fallback_unit
        if target_unit:
            price.unit = target_unit
            price.save(update_fields=['unit'])


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0007_alter_commodityunitmap_id'),
        ('markets', '0007_marketcommodityprice_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketcommodityprice',
            name='unit',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='market_prices',
                to='commodities.commodityunit',
            ),
        ),
        migrations.RunPython(
            set_default_commodity_unit_ids,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='marketcommodityprice',
            name='unit',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='market_prices',
                to='commodities.commodityunit',
            ),
            preserve_default=False,
        ),
    ]
