# Generated by Django 6.0.6 on 2026-08-02 01:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0008_rename_commodity_unit_maps'),
        ('markets', '0008_marketcommodityprice_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RawCommodityPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('price_type', models.CharField(blank=True, choices=[('retail', 'retail'), ('wholesale', 'wholesale')], max_length=32, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('TZS', 'TZS')], default='TZS', max_length=3)),
                ('source_key', models.CharField(max_length=50)),
                ('source_name', models.CharField(max_length=100)),
                ('source_reference', models.CharField(blank=True, max_length=255)),
                ('price_date', models.DateField()),
                ('observed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_prices', to='commodities.commodity')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_raw_commodity_prices', to=settings.AUTH_USER_MODEL)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_commodity_prices', to='markets.market')),
                ('normalized_price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_prices', to='markets.marketcommodityprice')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_market_prices', to='commodities.commodityunit')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_raw_commodity_prices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'raw_commodity_prices',
                'ordering': ['-price_date', 'market__name', 'commodity__name'],
                'indexes': [models.Index(fields=['source_key', 'price_date'], name='rcp_source_date_idx'), models.Index(fields=['market', 'price_date'], name='rcp_market_date_idx'), models.Index(fields=['commodity', 'price_date'], name='rcp_commodity_date_idx')],
            },
        ),
    ]
