# Generated by Codex on 2026-07-13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="AdmArea",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("public_id", models.CharField(editable=False, max_length=10, unique=True)),
                        ("name", models.CharField(max_length=150)),
                        (
                            "level",
                            models.CharField(
                                choices=[("region", "Region"), ("district", "District"), ("ward", "Ward")],
                                default="region",
                                max_length=50,
                            ),
                        ),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        (
                            "parent",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="children",
                                to="areas.admarea",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "adm_areas",
                        "ordering": ["name"],
                    },
                ),
            ],
        ),
    ]
