# Generated by Django 6.0.6 on 2026-07-30 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_integrations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='integratedmarketprice',
            name='imp_source_commodity_idx',
        ),
        migrations.RemoveIndex(
            model_name='integratedmarketprice',
            name='imp_commodity_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='integratedmarketprice',
            name='imp_market_time_idx',
        ),
        migrations.RemoveConstraint(
            model_name='integratedmarketprice',
            name='integrated_market_price_unique',
        ),
        migrations.DeleteModel(
            name='IntegratedMarketPrice',
        ),
    ]
