# Generated by Django 6.0.6 on 2026-08-16 03:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas', '0005_remove_admarea_adm_areas_parent_level_name_uniq_and_more'),
        ('commodities', '0008_rename_commodity_unit_maps'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandForecastRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('model_type', models.CharField(default='RandomForestRegressor', max_length=100)),
                ('model_path', models.CharField(blank=True, max_length=255)),
                ('metadata_path', models.CharField(blank=True, max_length=255)),
                ('training_started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('training_finished_at', models.DateTimeField(blank=True, null=True)),
                ('train_rows', models.PositiveIntegerField(default=0)),
                ('test_rows', models.PositiveIntegerField(default=0)),
                ('mae', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('rmse', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('status', models.CharField(default='training', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'demand_forecast_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DemandForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('week_start', models.DateField()),
                ('forecast_quantity', models.DecimalField(decimal_places=2, max_digits=14)),
                ('previous_week_demand', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('rolling_4_week_avg', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('rolling_8_week_avg', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('avg_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adm_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_forecasts', to='areas.admarea')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_forecasts', to='commodities.commodity')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='demand_forecasting.demandforecastrun')),
            ],
            options={
                'db_table': 'demand_forecasts',
                'ordering': ['week_start', 'commodity__name', 'adm_area__name'],
                'indexes': [models.Index(fields=['run', 'week_start'], name='df_run_week_idx'), models.Index(fields=['commodity', 'adm_area', 'week_start'], name='df_commodity_area_week_idx')],
                'constraints': [models.UniqueConstraint(fields=('run', 'commodity', 'adm_area', 'week_start'), name='unique_demand_forecast_row')],
            },
        ),
    ]
