# Generated by Django 6.0.6 on 2026-07-30 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegratedMarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('source_key', models.CharField(max_length=50)),
                ('source_name', models.CharField(max_length=100)),
                ('commodity', models.CharField(max_length=100)),
                ('market', models.CharField(blank=True, max_length=150, null=True)),
                ('price_tzs', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('delay_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('observed_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'integrated_market_prices',
                'ordering': ['-observed_at', 'source_key', 'commodity'],
                'indexes': [models.Index(fields=['source_key', 'commodity'], name='imp_source_commodity_idx'), models.Index(fields=['commodity', 'observed_at'], name='imp_commodity_time_idx'), models.Index(fields=['market', 'observed_at'], name='imp_market_time_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_key', 'commodity', 'market', 'observed_at'), name='integrated_market_price_unique')],
            },
        ),
    ]
