# Generated by Django 6.0.6 on 2026-08-06 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_integrations', '0003_marketintegrationsource'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketintegrationsource',
            name='sync_interval_hours',
            field=models.PositiveIntegerField(default=6, help_text='Number of hours to wait between automatic synchronizations.'),
        ),
    ]
