SYSTEM_PERMISSIONS = [
    ("auth.me", "View own profile", "Read the authenticated user's profile."),
    ("auth.logout", "Logout", "End the current authenticated session."),
    ("users.list", "List users", "List managed users."),
    ("users.create", "Create users", "Create managed users."),
    ("users.read", "Read users", "Read managed user details."),
    ("users.update", "Update users", "Update managed users."),
    ("users.delete", "Delete users", "Delete managed users."),
    ("roles.list", "List roles", "List system roles and role permission assignments."),
    ("roles.read", "Read roles", "Read a system role."),
    ("roles.permissions.update", "Update role permissions", "Assign system permissions to roles."),
    ("permissions.list", "List permissions", "List system-defined permissions."),
    ("permissions.read", "Read permissions", "Read a system-defined permission."),
    ("commodities.categories.list", "List commodity categories", "List commodity categories."),
    ("commodities.categories.create", "Create commodity categories", "Create commodity categories."),
    ("commodities.categories.read", "Read commodity categories", "Read commodity category details."),
    ("commodities.categories.update", "Update commodity categories", "Update commodity categories."),
    ("commodities.categories.delete", "Delete commodity categories", "Delete commodity categories."),
    ("commodities.units.list", "List commodity units", "List commodity measurement units."),
    ("commodities.units.create", "Create commodity units", "Create commodity measurement units."),
    ("commodities.units.read", "Read commodity units", "Read commodity measurement unit details."),
    ("commodities.units.update", "Update commodity units", "Update commodity measurement units."),
    ("commodities.units.delete", "Delete commodity units", "Delete commodity measurement units."),
    ("commodities.list", "List commodities", "List commodity catalog entries."),
    ("commodities.create", "Create commodities", "Create commodity catalog entries."),
    ("commodities.read", "Read commodities", "Read commodity catalog entry details."),
    ("commodities.update", "Update commodities", "Update commodity catalog entries."),
    ("commodities.delete", "Delete commodities", "Delete commodity catalog entries."),
    ("areas.create", "Create areas", "Create administrative areas."),
    ("areas.bulk_import", "Bulk import areas", "Bulk import administrative area paths."),
    ("areas.update", "Update areas", "Update administrative areas."),
    ("areas.delete", "Delete areas", "Delete administrative areas."),
    ("listings.create", "Create listings", "Create commodity listings."),
    ("listings.update", "Update listings", "Update commodity listings."),
    ("listings.delete", "Delete listings", "Delete commodity listings."),
    ("orders.list", "List orders", "List visible orders."),
    ("orders.create", "Create orders", "Create orders."),
    ("orders.read", "Read orders", "Read order details."),
    ("orders.update", "Update orders", "Update orders."),
]
