SYSTEM_PERMISSIONS = [
    ("auth.me", "View own profile", "Read the authenticated user's profile."),
    ("auth.account.delete", "Delete own account", "Delete the authenticated user's own account."),
    ("auth.logout", "Logout", "End the current authenticated session."),
    ("users.list", "List users", "List managed users."),
    ("users.create", "Create users", "Create managed users."),
    ("users.read", "Read users", "Read managed user details."),
    ("users.update", "Update users", "Update managed users."),
    ("users.delete", "Delete users", "Delete managed users."),
    ("roles.list", "List roles", "List system roles and role permission assignments."),
    ("roles.create", "Create roles", "Create custom roles."),
    ("roles.read", "Read roles", "Read a system role."),
    ("roles.update", "Update roles", "Update role metadata."),
    ("roles.delete", "Delete roles", "Delete custom roles."),
    ("roles.permissions.update", "Update role permissions", "Assign system permissions to roles."),
    ("permissions.list", "List permissions", "List system-defined permissions."),
    ("permissions.read", "Read permissions", "Read a system-defined permission."),
    ("commodities.categories.list", "List commodity categories", "List commodity categories."),
    ("commodities.categories.create", "Create commodity categories", "Create commodity categories."),
    ("commodities.categories.read", "Read commodity categories", "Read commodity category details."),
    ("commodities.categories.update", "Update commodity categories", "Update commodity categories."),
    ("commodities.categories.delete", "Delete commodity categories", "Delete commodity categories."),
    ("commodities.units.list", "List commodity units", "List commodity measurement units."),
    ("commodities.units.create", "Create commodity units", "Create commodity measurement units."),
    ("commodities.units.read", "Read commodity units", "Read commodity measurement unit details."),
    ("commodities.units.update", "Update commodity units", "Update commodity measurement units."),
    ("commodities.units.delete", "Delete commodity units", "Delete commodity measurement units."),
    ("commodities.list", "List commodities", "List commodity catalog entries."),
    ("commodities.create", "Create commodities", "Create commodity catalog entries."),
    ("commodities.read", "Read commodities", "Read commodity catalog entry details."),
    ("commodities.update", "Update commodities", "Update commodity catalog entries."),
    ("commodities.delete", "Delete commodities", "Delete commodity catalog entries."),
    ("markets.list", "List markets", "List markets."),
    ("markets.create", "Create markets", "Create markets."),
    ("markets.read", "Read markets", "Read market details."),
    ("markets.update", "Update markets", "Update markets."),
    ("markets.delete", "Delete markets", "Delete markets."),
    ("market_prices.list", "List market prices", "List market commodity prices."),
    ("market_prices.create", "Create market prices", "Create market commodity prices."),
    ("market_prices.read", "Read market prices", "Read market commodity price details."),
    ("market_prices.update", "Update market prices", "Update market commodity prices."),
    ("market_prices.delete", "Delete market prices", "Delete market commodity prices."),
    ("market_prices.latest", "View latest market prices", "View latest prices for commodities in a market."),
    ("commodity_prices.list", "List commodity prices", "List prices for a commodity across markets."),
    ("commodity_prices.history", "View commodity price history", "View commodity price history across markets."),
    ("commodity_prices.compare", "Compare commodity prices", "Compare commodity prices across markets."),
    ("areas.list", "List areas", "List administrative areas."),
    ("areas.read", "Read areas", "Read administrative area details."),
    ("areas.create", "Create areas", "Create administrative areas."),
    ("areas.bulk_import", "Bulk import areas", "Bulk import administrative area paths."),
    ("areas.update", "Update areas", "Update administrative areas."),
    ("areas.delete", "Delete areas", "Delete administrative areas."),
    ("listings.list", "List listings", "List commodity listings."),
    ("listings.read", "Read listings", "Read commodity listing details."),
    ("listings.create", "Create listings", "Create commodity listings."),
    ("listings.update", "Update listings", "Update commodity listings."),
    ("listings.delete", "Delete listings", "Delete commodity listings."),
    ("orders.list", "List orders", "List visible orders."),
    ("orders.create", "Create orders", "Create orders."),
    ("orders.read", "Read orders", "Read order details."),
    ("orders.update", "Update orders", "Update orders."),
]

SYSTEM_ROLES = [
    ("admin", "Administrator", "Full system administration role.", True),
    ("farmer", "Farmer", "Commodity producer role.", True),
    ("entrepreneur", "Entrepreneur", "Trading and selling role.", True),
    ("buyer", "Buyer", "Commodity purchasing role.", True),
    ("market_officer", "Market Officer", "Market data collection and validation role.", True),
]

DEFAULT_ROLE_PERMISSIONS = {
    "admin": [code for code, _name, _description in SYSTEM_PERMISSIONS],
    "farmer": [
        "auth.me",
        "auth.account.delete",
        "auth.logout",
        "commodities.list",
        "commodities.read",
        "markets.list",
        "markets.read",
        "market_prices.list",
        "market_prices.read",
        "market_prices.latest",
        "commodity_prices.list",
        "commodity_prices.history",
        "commodity_prices.compare",
        "areas.list",
        "areas.read",
        "listings.list",
        "listings.read",
        "listings.create",
        "listings.update",
        "listings.delete",
        "orders.list",
        "orders.read",
        "orders.update",
    ],
    "entrepreneur": [
        "auth.me",
        "auth.account.delete",
        "auth.logout",
        "commodities.list",
        "commodities.read",
        "markets.list",
        "markets.read",
        "market_prices.list",
        "market_prices.read",
        "market_prices.latest",
        "commodity_prices.list",
        "commodity_prices.history",
        "commodity_prices.compare",
        "areas.list",
        "areas.read",
        "listings.list",
        "listings.read",
        "listings.create",
        "listings.update",
        "listings.delete",
        "orders.list",
        "orders.read",
        "orders.update",
    ],
    "buyer": [
        "auth.me",
        "auth.account.delete",
        "auth.logout",
        "commodities.list",
        "commodities.read",
        "markets.list",
        "markets.read",
        "market_prices.list",
        "market_prices.read",
        "market_prices.latest",
        "commodity_prices.list",
        "commodity_prices.history",
        "commodity_prices.compare",
        "areas.list",
        "areas.read",
        "listings.list",
        "listings.read",
        "orders.create",
        "orders.list",
        "orders.read",
    ],
    "market_officer": [
        "auth.me",
        "auth.account.delete",
        "auth.logout",
        "commodities.list",
        "commodities.read",
        "markets.list",
        "markets.read",
        "market_prices.list",
        "market_prices.create",
        "market_prices.read",
        "market_prices.update",
        "market_prices.latest",
        "commodity_prices.list",
        "commodity_prices.history",
        "commodity_prices.compare",
        "areas.list",
        "areas.read",
        "areas.create",
        "areas.bulk_import",
        "areas.update",
    ],
}
