# Generated by Django 6.0.6 on 2026-08-19 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demand_forecasting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandforecastrun',
            name='metadata_path',
        ),
    ]
