# Generated by Django 6.0.6 on 2026-07-14 06:07

import django.db.models.deletion
from django.db import migrations, models


def clear_role_permissions(apps, schema_editor):
    RolePermission = apps.get_model("users", "RolePermission")
    RolePermission.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_seed_system_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'roles',
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(clear_role_permissions, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_links', to='users.role'),
        ),
    ]
