# Generated by Django 6.0.6 on 2026-07-29 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_email_verification_token_user_fk_cascade'),
        ('api', '0007_merge_20260728_0001'),
    ]

    operations = [
    ]
