# Generated by Django 6.0.6 on 2026-07-10 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_profile_public_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='emailverificationtoken',
            table='email_verification_tokens',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='users_profiles',
        ),
    ]
