# Generated by Codex on 2026-07-28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_profile_farm_fields"),
        ("api", "0006_profile_role_fk"),
    ]

    operations = []
