# Generated by Django 6.0.6 on 2026-07-28 18:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0005_merge_20260728_0001'),
        ('markets', '0002_marketcommodityprice_min_max_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='marketcommodityprice',
            name='market_commodity_price_unique',
        ),
        migrations.AddField(
            model_name='marketcommodityprice',
            name='pricetype',
            field=models.CharField(blank=True, choices=[('Retail', 'Retail'), ('Wholesale', 'Wholesale')], max_length=32, null=True),
        ),
        migrations.AddConstraint(
            model_name='marketcommodityprice',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('market', 'commodity', 'price_date', 'pricetype'), name='market_commodity_price_unique'),
        ),
    ]
