# Generated by Django 6.0.6 on 2026-07-30 05:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0005_merge_20260728_0001'),
        ('markets', '0003_remove_marketcommodityprice_market_commodity_price_unique_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='marketcommodityprice',
            name='price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='marketcommodityprice',
            name='source_key',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='marketcommodityprice',
            name='source_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='marketcommodityprice',
            index=models.Index(fields=['source_key', 'commodity'], name='mcp_source_commodity_idx'),
        ),
    ]
