# Generated by Django 6.0.6 on 2026-07-18 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0002_market'),
        ('ussd', '0002_ussdsubscriber_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UssdMarketPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(choices=[('Beans', 'Beans'), ('Rice', 'Rice')], max_length=32)),
                ('pricetype', models.CharField(choices=[('Retail', 'Retail'), ('Wholesale', 'Wholesale')], max_length=32)),
                ('unit', models.CharField(max_length=32)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('seasonal', 'Seasonal')], max_length=32)),
                ('target_date', models.DateField()),
                ('period_end', models.DateField()),
                ('season', models.CharField(max_length=64)),
                ('predicted_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='TZS', max_length=16)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ussd_predictions', to='commodities.market')),
            ],
            options={
                'ordering': ['market__name', 'commodity', 'pricetype', 'period', '-target_date'],
                'constraints': [models.UniqueConstraint(fields=('market', 'commodity', 'pricetype', 'period', 'target_date'), name='unique_ussd_market_prediction_per_date')],
            },
        ),
    ]
