# Generated by Django 6.0.6 on 2026-07-18 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0003_seed_prediction_commodities'),
        ('ussd', '0003_ussdmarketprediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='UssdMarketRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('farmer', 'Farmer'), ('entrepreneur', 'Entrepreneur'), ('buyer', 'Buyer')], max_length=32)),
                ('commodity', models.CharField(choices=[('Beans', 'Beans'), ('Rice', 'Rice')], max_length=32)),
                ('recommendation_type', models.CharField(choices=[('time', 'Time'), ('market', 'Market')], max_length=16)),
                ('action', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=16)),
                ('target_date', models.DateField()),
                ('period', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('seasonal', 'Seasonal')], max_length=32, null=True)),
                ('season', models.CharField(max_length=64)),
                ('trend', models.CharField(choices=[('rising', 'Rising'), ('falling', 'Falling'), ('stable', 'Stable')], max_length=16)),
                ('recommended_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='TZS', max_length=16)),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=5)),
                ('summary', models.CharField(max_length=255)),
                ('reason', models.TextField()),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ussd_recommendations', to='commodities.market')),
            ],
            options={
                'ordering': ['role', 'commodity', 'recommendation_type', '-target_date'],
                'constraints': [models.UniqueConstraint(fields=('role', 'commodity', 'recommendation_type', 'target_date'), name='unique_ussd_market_recommendation_per_date')],
            },
        ),
    ]
