# Generated by Django 6.0.6 on 2026-07-18 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0004_ussdmarketrecommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='ussdmarketrecommendation',
            name='window_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ussdmarketrecommendation',
            name='window_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
