# Generated by Django 6.0.6 on 2026-07-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_listingimage_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admarea',
            old_name='area_type',
            new_name='level',
        ),
        migrations.AlterField(
            model_name='admarea',
            name='level',
            field=models.CharField(choices=[('region', 'Region'), ('district', 'District'), ('ward', 'Ward')], default='region', max_length=50),
        ),
    ]
