# Generated by Codex on 2026-07-13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("areas", "0001_initial"),
        ("listings", "0003_remove_admarea_area_type_admarea_level"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name="commoditylisting",
                    name="adm_area",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listings",
                        to="areas.admarea",
                    ),
                ),
                migrations.DeleteModel(name="AdmArea"),
            ],
        ),
    ]
