# Generated by Django 6.0.6 on 2026-07-19 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0003_seed_prediction_commodities'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPriceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('price_type', models.CharField(choices=[('Retail', 'Retail'), ('Wholesale', 'Wholesale')], max_length=32)),
                ('unit', models.CharField(max_length=32)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='TZS', max_length=16)),
                ('record_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_records', to='commodities.commodity')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_price_records', to=settings.AUTH_USER_MODEL)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_records', to='commodities.market')),
            ],
            options={
                'ordering': ['-record_date', 'market__name', 'commodity__name'],
            },
        ),
    ]
