# Generated by Codex on 2026-07-28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commodities", "0003_commodityunit_commodity_unit_ref"),
        ("commodities", "0004_marketpricerecord"),
    ]

    operations = []
