# Generated by Django 6.0.6 on 2026-07-31 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0006_commodity_unit_m2m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodityunitmap',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
