# Generated by Django 6.0.6 on 2026-07-01 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'commodities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CommodityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'commodity categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CommodityCategoryMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodities.commoditycategory')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodities.commodity')),
            ],
        ),
        migrations.AddField(
            model_name='commodity',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='commodities', through='commodities.CommodityCategoryMap', to='commodities.commoditycategory'),
        ),
        migrations.AddConstraint(
            model_name='commoditycategorymap',
            constraint=models.UniqueConstraint(fields=('commodity', 'category'), name='unique_commodity_category_map'),
        ),
    ]
