# Generated by Django 6.0.6 on 2026-07-10 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='commodity',
            table='commodities',
        ),
        migrations.AlterModelTable(
            name='commoditycategory',
            table='commodity_categories',
        ),
        migrations.AlterModelTable(
            name='commoditycategorymap',
            table='commodity_category_maps',
        ),
    ]
