# Generated by Django 6.0.6 on 2026-07-14 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0002_alter_commodity_table_alter_commoditycategory_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommodityUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('symbol', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'commodity units',
                'db_table': 'commodity_units',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='commodity',
            name='unit_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commodities', to='commodities.commodityunit'),
        ),
    ]
