# Generated by Codex on 2026-07-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("areas", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="admarea",
            index=models.Index(fields=["parent", "level", "name"], name="adm_areas_path_idx"),
        ),
    ]
