# Generated by Django 6.0.6 on 2026-07-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0002_admarea_path_index'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='admarea',
            constraint=models.UniqueConstraint(fields=('level', 'name'), name='adm_areas_level_name_uniq'),
        ),
    ]
