# Generated by Django 6.0.6 on 2026-07-20 17:46

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0004_drop_adm_areas_level_name_uniq'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='admarea',
            name='adm_areas_parent_level_name_uniq',
        ),
        migrations.AddConstraint(
            model_name='admarea',
            constraint=models.UniqueConstraint(models.F('parent'), models.F('level'), django.db.models.functions.text.Lower('name'), name='adm_areas_parent_level_lower_name_uniq'),
        ),
    ]
